package com.example.ui.localization

import com.example.data.model.IndianLanguage

object LocalizationManager {

    fun getString(key: String, lang: IndianLanguage): String {
        return translations[key]?.get(lang)
            ?: translations[key]?.get(IndianLanguage.HINDI)
            ?: translations[key]?.get(IndianLanguage.ENGLISH)
            ?: key
    }

    private val translations = mapOf(
        "app_title" to mapOf(
            IndianLanguage.ENGLISH to "RailSathi",
            IndianLanguage.HINDI to "रेल साथी",
            IndianLanguage.BENGALI to "রেল সাথী",
            IndianLanguage.MARATHI to "रेल साथी",
            IndianLanguage.TAMIL to "ரயில் சாதி",
            IndianLanguage.TELUGU to "రైల్ సాథి",
            IndianLanguage.GUJARATI to "રેલ સાથી",
            IndianLanguage.KANNADA to "ರೈಲ್ ಸಾಥಿ",
            IndianLanguage.ODIA to "ରେଲ ସାଥୀ",
            IndianLanguage.PUNJABI to "ਰੇਲ ਸਾਥੀ",
            IndianLanguage.MALAYALAM to "റെയിൽ സാഥി"
        ),
        "app_tagline" to mapOf(
            IndianLanguage.ENGLISH to "Local Train Food & Vendor Connect",
            IndianLanguage.HINDI to "लोकल ट्रेन में ताज़ा नाश्ता व फेरीवाला संपर्क",
            IndianLanguage.BENGALI to "লোকাল ট্রেনে খাবার ও হকার সংযোগ",
            IndianLanguage.MARATHI to "लोकल ट्रेनमधील खाद्यपदार्थ व फेरीवाले नेटवर्क",
            IndianLanguage.TAMIL to "உள்ளூர் ரயில் உணவு & வியாபாரி இணைப்பு",
            IndianLanguage.TELUGU to "లోకల్ రైలు ఆహారం & విక్రేత కనెక్ట్",
            IndianLanguage.GUJARATI to "લોકલ ટ્રેનમાં તાજો નાસ્તો અને ફેરિયા કનેક્ટ",
            IndianLanguage.KANNADA to "ಲೋಕಲ್ ರೈಲು ಆಹಾರ & ಮಾರಾಟಗಾರ ಸಂಪರ್ಕ",
            IndianLanguage.ODIA to "ଲୋକାଲ ଟ୍ରେନରେ ଖାଦ୍ୟ ଓ ବିକ୍ରେତା ସଂଯୋଗ",
            IndianLanguage.PUNJABI to "ਲੋਕਲ ਟ੍ਰੇਨ ਭੋਜਨ ਅਤੇ ਵਿਕਰੇਤਾ ਸੰਪਰਕ",
            IndianLanguage.MALAYALAM to "ലോക്കൽ ട്രെയിൻ ഭക്ഷണവും വെണ്ടർ കണക്റ്റും"
        ),
        "role_select_title" to mapOf(
            IndianLanguage.ENGLISH to "Choose Your Role",
            IndianLanguage.HINDI to "अपनी भूमिका चुनें",
            IndianLanguage.BENGALI to "আপনার ভূমিকা নির্বাচন করুন",
            IndianLanguage.MARATHI to "तुमची भूमिका निवडा",
            IndianLanguage.TAMIL to "உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்",
            IndianLanguage.TELUGU to "మీ పాత్రను ఎంచుకోండి",
            IndianLanguage.GUJARATI to "તમારી ભૂમિકા પસંદ કરો",
            IndianLanguage.KANNADA to "ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            IndianLanguage.ODIA to "ଆପଣଙ୍କ ଭୂମିକା ଚୟନ କରନ୍ତୁ",
            IndianLanguage.PUNJABI to "ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ",
            IndianLanguage.MALAYALAM to "നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക"
        ),
        "role_passenger" to mapOf(
            IndianLanguage.ENGLISH to "Train Traveler / Passenger",
            IndianLanguage.HINDI to "ट्रेन यात्री / दैनिक मुसाफिर",
            IndianLanguage.BENGALI to "ট্রেন যাত্রী / সাধারণ মানুষ",
            IndianLanguage.MARATHI to "रेल्वे प्रवासी / नागरिक",
            IndianLanguage.TAMIL to "ரயில் பயணி / பொது மக்கள்",
            IndianLanguage.TELUGU to "రైలు ప్రయాణీకుడు / ప్రజలు",
            IndianLanguage.GUJARATI to "ટ્રેન મુસાફર / સામાન્ય જનતા",
            IndianLanguage.KANNADA to "ರೈಲು ಪ್ರಯಾಣಿಕ / ಸಾರ್ವಜನಿಕರು",
            IndianLanguage.ODIA to "ଟ୍ରେନ୍ ଯାତ୍ରୀ / ସାଧାରଣ ଲୋକ",
            IndianLanguage.PUNJABI to "ਟ੍ਰੇਨ ਯਾਤਰੀ / ਆਮ ਜਨਤਾ",
            IndianLanguage.MALAYALAM to "ട്രെയിൻ യാത്രക്കാരൻ / പൊതുജനം"
        ),
        "role_passenger_desc" to mapOf(
            IndianLanguage.ENGLISH to "Order fresh snacks inside your coach during travel and track daily budget",
            IndianLanguage.HINDI to "सफ़र के दौरान अपनी बोगी में ताज़ा नाश्ता मँगवाएं और मासिक खर्च ट्रैक करें",
            IndianLanguage.BENGALI to "যাত্রার সময় নিজের কামরায় খাবার অর্ডার করুন ও খরচের হিসাব রাখুন",
            IndianLanguage.MARATHI to "प्रवासादरम्यान आपल्या डब्यात नाश्ता मागवा आणि खर्च ट्रॅक करा",
            IndianLanguage.TAMIL to "பயணத்தின் போது உங்கள் பெட்டியில் சிற்றுண்டி ஆர்டர் செய்து பட்ஜெட்டை கண்காணிக்கவும்",
            IndianLanguage.TELUGU to "ప్రయాణంలో మీ కోచ్‌లోనే తాజా స్నాక్స్ ఆర్డర్ చేయండి",
            IndianLanguage.GUJARATI to "મુસાફરી દરમિયાન તમારા કોચમાં નાસ્તો મંગાવો અને બજેટ ટ્રેક કરો",
            IndianLanguage.KANNADA to "ಪ್ರಯಾಣದ ಸಮಯದಲ್ಲಿ ನಿಮ್ಮ ಕೋಚ್‌ನಲ್ಲಿ ತಿಂಡಿಗಳನ್ನು ತರಿಸಿ",
            IndianLanguage.ODIA to "ଯାତ୍ରା ସମୟରେ ଆପଣଙ୍କ ବଗିରେ ଖାଦ୍ୟ ମଗାନ୍ତୁ",
            IndianLanguage.PUNJABI to "ਸਫ਼ਰ ਦੌਰਾਨ ਆਪਣੀ ਬੋਗੀ ਵਿੱਚ ਤਾਜ਼ਾ ਨਾਸ਼ਤਾ ਮੰਗਵਾਓ",
            IndianLanguage.MALAYALAM to "യാത്രയിൽ നിങ്ങളുടെ കോച്ചിൽ ഭക്ഷണം ഓർഡർ ചെയ്യുക"
        ),
        "role_vendor" to mapOf(
            IndianLanguage.ENGLISH to "Train Hawker / Vendor",
            IndianLanguage.HINDI to "फेरीवाला / वेंडर (विक्रेता)",
            IndianLanguage.BENGALI to "ট্রেন হকার / বিক্রেতা",
            IndianLanguage.MARATHI to "रेल्वे फेरीवाला / विक्रेता",
            IndianLanguage.TAMIL to "ரயில் வியாபாரி",
            IndianLanguage.TELUGU to "రైలు విక్రేత / హాకర్",
            IndianLanguage.GUJARATI to "ટ્રેન ફેરિયો / વિક્રેતા",
            IndianLanguage.KANNADA to "ರೈಲು ವ್ಯಾಪಾರಿ",
            IndianLanguage.ODIA to "ଟ୍ରେନ୍ ବିକ୍ରେତା",
            IndianLanguage.PUNJABI to "ਟ੍ਰੇਨ ਵਿਕਰੇਤਾ",
            IndianLanguage.MALAYALAM to "ട്രെയിൻ വെണ്ടർ"
        ),
        "role_vendor_desc" to mapOf(
            IndianLanguage.ENGLISH to "See hungry passenger coaches, avoid same-item vendor collision, and get fair orders",
            IndianLanguage.HINDI to "भूखे यात्रियों की बोगी देखें, एक ही कोच में टकराव से बचें और निष्पक्ष आय कमाएं",
            IndianLanguage.BENGALI to "যাত্রীদের চাহিদা দেখুন, একই কামরায় একই বিক্রেতার ভিড় এড়ান ও লাভ বাড়ান",
            IndianLanguage.MARATHI to "प्रवाशांची मागणी पहा, एकाच डब्यात गर्दी टाळा आणि समान कमाई मिळवा",
            IndianLanguage.TAMIL to "பயணிகளின் தேவையை அறிந்து சமமான வருமானம் பெறுங்கள்",
            IndianLanguage.TELUGU to "ప్రయాణీకుల ఆర్డర్లు చూసి సమాన ఆదాయం పొందండి",
            IndianLanguage.GUJARATI to "મુસાફરોની માંગ જુઓ અને વધુ નફો મેળવો",
            IndianLanguage.KANNADA to "ಪ್ರಯಾಣಿಕರ ಬೇಡಿಕೆ ನೋಡಿ ಉತ್ತಮ ಆದಾಯ ಗಳಿಸಿ",
            IndianLanguage.ODIA to "ଯାତ୍ରୀଙ୍କ ଚାହିଦା ଦେଖି ବିକ୍ରି କରନ୍ତୁ",
            IndianLanguage.PUNJABI to "ਯਾਤਰੀਆਂ ਦੀ ਮੰਗ ਦੇਖ ਕੇ ਸਹੀ ਕਮਾਈ ਕਰੋ",
            IndianLanguage.MALAYALAM to "യാത്രക്കാരുടെ ആവശ്യം കണ്ട് കൂടുതൽ വിൽക്കുക"
        ),
        "role_guest" to mapOf(
            IndianLanguage.ENGLISH to "Continue as Guest",
            IndianLanguage.HINDI to "अतिथि के रूप में आगे बढ़ें",
            IndianLanguage.BENGALI to "গেস্ট হিসেবে এগিয়ে চলুন",
            IndianLanguage.MARATHI to "पाहुणे म्हणून सुरू ठेवा",
            IndianLanguage.TAMIL to "விருந்தினராக தொடரவும்",
            IndianLanguage.TELUGU to "అతిథిగా కొనసాగండి",
            IndianLanguage.GUJARATI to "મહેમાન તરીકે આગળ વધો",
            IndianLanguage.KANNADA to "ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಯಿರಿ",
            IndianLanguage.ODIA to "ଅତିଥି ଭାବରେ ଆଗକୁ ବଢ଼ନ୍ତୁ",
            IndianLanguage.PUNJABI to "ਮਹਿਮਾਨ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ",
            IndianLanguage.MALAYALAM to "ഗസ്റ്റായി തുടരുക"
        ),
        "senior_mode" to mapOf(
            IndianLanguage.ENGLISH to "Senior Citizen Mode",
            IndianLanguage.HINDI to "वरिष्ठ नागरिक सुविधा (बड़ा टेक्स्ट व सरल बटन)",
            IndianLanguage.BENGALI to "বয়োজ্যেষ্ঠ সুবিধা (বড় লেখা ও সহজ বোতাম)",
            IndianLanguage.MARATHI to "ज्येष्ठ नागरिक मोड (मोठे मजकूर व सोपे बटणे)",
            IndianLanguage.TAMIL to "முதியோர் பயன்முறை (பெரிய எழுத்துக்கள்)",
            IndianLanguage.TELUGU to "సీనియర్ సిటిజన్ మోడ్ (పెద్ద అక్షరాలు)",
            IndianLanguage.GUJARATI to "વરિષ્ઠ નાગરિક મોડ (મોટા અક્ષરો)",
            IndianLanguage.KANNADA to "ಹಿರಿಯ ನಾಗರಿಕರ ಮೋಡ್",
            IndianLanguage.ODIA to "ବରିଷ୍ଠ ନାଗରିକ ସୁବିଧା",
            IndianLanguage.PUNJABI to "ਬਜ਼ੁਰਗ ਮੋਡ",
            IndianLanguage.MALAYALAM to "മുതിർന്ന പൗരന്മാർക്കുള്ള മോഡ്"
        ),
        "senior_mode_subtitle" to mapOf(
            IndianLanguage.ENGLISH to "Large fonts, soft food filters, and high contrast buttons",
            IndianLanguage.HINDI to "आंखों के लिए आरामदायक, नरम भोजन विकल्प व एक-टैप सहायता",
            IndianLanguage.BENGALI to "সহজবোধ্য ইন্টারফেস ও নরম খাবারের বিকল্প",
            IndianLanguage.MARATHI to "वाचायला सोपे, मऊ अन्नाचे पर्याय आणि मोठा आकार",
            IndianLanguage.TAMIL to "எளிதில் படிக்கக்கூடிய எழுத்துகள் மற்றும் மென்மையான உணவு",
            IndianLanguage.TELUGU to "చదవడానికి సులభం మరియు మృదువైన ఆహార ఎంపికలు",
            IndianLanguage.GUJARATI to "વાંચવામાં સરળ અને નરમ ખોરાકના વિકલ્પો",
            IndianLanguage.KANNADA to "ಓದಲು ಸುಲಭ ಮತ್ತು ಮೃದು ಆಹಾರದ ಆಯ್ಕೆಗಳು",
            IndianLanguage.ODIA to "ପଢ଼ିବା ସହଜ ଏବଂ ନରମ ଖାଦ୍ୟ ବିକଳ୍ପ",
            IndianLanguage.PUNJABI to "ਪੜ੍ਹਨ ਵਿੱਚ ਆਸਾਨ ਅਤੇ ਨਰਮ ਖਾਣਾ",
            IndianLanguage.MALAYALAM to "വായിക്കാൻ എളുപ്പവും മൃദുവായ ഭക്ഷണവും"
        ),
        "language_select" to mapOf(
            IndianLanguage.ENGLISH to "Select Language / भाषा चुनें",
            IndianLanguage.HINDI to "भाषा बदलें",
            IndianLanguage.BENGALI to "ভাষা নির্বাচন",
            IndianLanguage.MARATHI to "भाषा निवडा",
            IndianLanguage.TAMIL to "மொழியைத் தேர்வுசெய்க",
            IndianLanguage.TELUGU to "భాషను ఎంచుకోండి",
            IndianLanguage.GUJARATI to "ભાષા પસંદ કરો",
            IndianLanguage.KANNADA to "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            IndianLanguage.ODIA to "ଭାଷା ବଦଳାନ୍ତୁ",
            IndianLanguage.PUNJABI to "ਭਾਸ਼ਾ ਚੁਣੋ",
            IndianLanguage.MALAYALAM to "ഭാഷ തിരഞ്ഞെടുക്കുക"
        ),
        "hunger_signal_title" to mapOf(
            IndianLanguage.ENGLISH to "Hungry? Signal Nearby Vendors",
            IndianLanguage.HINDI to "भूख लगी है? आसपास के फेरीवालों को बुलाएं",
            IndianLanguage.BENGALI to "ক্ষিদে পেয়েছে? কাছের হকারদের জানান",
            IndianLanguage.MARATHI to "भूख लागली आहे? जवळील विक्रेत्यांना बोलवा",
            IndianLanguage.TAMIL to "பசிக்கிறதா? அருகிலுள்ள வியாபாரிகளை அழைக்கவும்",
            IndianLanguage.TELUGU to "ఆకలిగా ఉందా? సమీప విక్రేతలను పిలవండి",
            IndianLanguage.GUJARATI to "ભૂખ લાગી છે? નજીકના ફેરિયાઓને બોલાવો",
            IndianLanguage.KANNADA to "ಹಸಿವಾಗಿದೆಯೇ? ಸಮೀಪದ ವ್ಯಾಪಾರಿಗಳನ್ನು ಕರೆಯಿರಿ",
            IndianLanguage.ODIA to "ଭୋକ ଲାଗିଛି? ପାଖ ବିକ୍ରେତାଙ୍କୁ ଡାକନ୍ତୁ",
            IndianLanguage.PUNJABI to "ਭੁੱਖ ਲੱਗੀ ਹੈ? ਨੇੜਲੇ ਵਿਕਰੇਤਾਵਾਂ ਨੂੰ ਬੁਲਾਓ",
            IndianLanguage.MALAYALAM to "വിശക്കുന്നുണ്ടോ? അടുത്തുള്ള വെണ്ടർമാരെ അറിയിക്കൂ"
        ),
        "select_coach" to mapOf(
            IndianLanguage.ENGLISH to "Your Coach / Compartment",
            IndianLanguage.HINDI to "आपकी बोगी / कोच चुनें",
            IndianLanguage.BENGALI to "আপনার কামরা / কোচ বাছুন",
            IndianLanguage.MARATHI to "तुमचा डबा / कोच निवडा",
            IndianLanguage.TAMIL to "உங்கள் பெட்டி / கோச்",
            IndianLanguage.TELUGU to "మీ కోచ్ / కంపార్ట్మెంట్",
            IndianLanguage.GUJARATI to "તમારો ડબ્બો / કોચ",
            IndianLanguage.KANNADA to "ನಿಮ್ಮ ಕೋಚ್ / ಬೋಗಿ",
            IndianLanguage.ODIA to "ଆପଣଙ୍କ ବଗି / କୋଚ୍",
            IndianLanguage.PUNJABI to "ਤੁਹਾਡੀ ਬੋਗੀ / ਕੋਚ",
            IndianLanguage.MALAYALAM to "നിങ്ങളുടെ കോച്ച്"
        ),
        "seat_desc" to mapOf(
            IndianLanguage.ENGLISH to "Seat / Window / Door location (optional)",
            IndianLanguage.HINDI to "सीट / खिड़की / दरवाज़ा विवरण (वैकल्पिक)",
            IndianLanguage.BENGALI to "সিট / জানলা / দরজার বিবরণ (ঐচ্ছিক)",
            IndianLanguage.MARATHI to "सीट / खिडकी / दरवाजा तपशील",
            IndianLanguage.TAMIL to "இருக்கை / ஜன்னல் விவரம்",
            IndianLanguage.TELUGU to "సీటు / కిటికీ వివరాలు",
            IndianLanguage.GUJARATI to "સીટ / બારી વિગત",
            IndianLanguage.KANNADA to "ಸೀಟ್ / ಕಿಟಕಿ ವಿವರ",
            IndianLanguage.ODIA to "ସିଟ୍ / ଝରକା ବିବରଣୀ",
            IndianLanguage.PUNJABI to "ਸੀਟ / ਖਿੜਕੀ ਵੇਰਵਾ",
            IndianLanguage.MALAYALAM to "സീറ്റ് / ജനൽ വിവരങ്ങൾ"
        ),
        "send_signal_btn" to mapOf(
            IndianLanguage.ENGLISH to "Signal Vendors Now (₹0)",
            IndianLanguage.HINDI to "फेरीवाले को तुरंत संकेत भेजें",
            IndianLanguage.BENGALI to "হকারকে সংকেত পাঠান",
            IndianLanguage.MARATHI to "विक्रेत्याला आताच संदेश पाठवा",
            IndianLanguage.TAMIL to "இப்போதே சமிக்ஞை அனுப்பவும்",
            IndianLanguage.TELUGU to "ఇప్పుడే సంకేతం పంపండి",
            IndianLanguage.GUJARATI to "ફેરિયાને સંકેત મોકલો",
            IndianLanguage.KANNADA to "ಈಗಲೇ ಸಂಕೇತ ಕಳುಹಿಸಿ",
            IndianLanguage.ODIA to "ବର୍ତ୍ତମାନ ସଙ୍କେତ ପଠାନ୍ତୁ",
            IndianLanguage.PUNJABI to "ਹੁਣੇ ਸੰਕੇਤ ਭੇਜੋ",
            IndianLanguage.MALAYALAM to "ഇപ്പോൾ സിഗ്നൽ അയക്കൂ"
        ),
        "collision_prevented" to mapOf(
            IndianLanguage.ENGLISH to "Coach Conflict Guard",
            IndianLanguage.HINDI to "कोच सुरक्षा जांच: कोई टकराव नहीं",
            IndianLanguage.BENGALI to "একই খাবারের হকার প্রতিরোধ ব্যবস্থা",
            IndianLanguage.MARATHI to "डब्यातील गर्दी नियंत्रण",
            IndianLanguage.TAMIL to "பெட்டி மோதல் தடுப்பு",
            IndianLanguage.TELUGU to "కోచ్ వివాద రక్షణ",
            IndianLanguage.GUJARATI to "કોચ તકરાર નિયંત્રણ",
            IndianLanguage.KANNADA to "ಕೋಚ್ ಸಂಘರ್ಷ ನಿಯಂತ್ರಣ",
            IndianLanguage.ODIA to "ବଗି ବିବାଦ ନିୟନ୍ତ୍ରଣ",
            IndianLanguage.PUNJABI to "ਬੋਗੀ ਟਕਰਾਅ ਰੋਕਥਾਮ",
            IndianLanguage.MALAYALAM to "കോച്ച് തർക്ക പ്രതിരോധം"
        ),
        "collision_warning_text" to mapOf(
            IndianLanguage.ENGLISH to "Another vendor is already selling this item in Coach {coach}. Switch to Coach {altCoach} with high hungry passengers!",
            IndianLanguage.HINDI to "कोच {coach} में पहले से यह सामान बेचने वाला वेंडर मौजूद है। खाली मांग वाले कोच {altCoach} में जाएं!",
            IndianLanguage.BENGALI to "কোচ {coach}-এ ইতিমধ্যেই এই খাবারের বিক্রেতা আছেন। অধিক চাহিদার কোচ {altCoach}-এ যান!",
            IndianLanguage.MARATHI to "डबा {coach} मध्ये आधीच हा विक्रेता आहे. डबा {altCoach} मध्ये जा!",
            IndianLanguage.TAMIL to "கோச் {coach}-ல் ஏற்கனவே இந்த வியாபாரி உள்ளார். கோச் {altCoach}-க்கு செல்லவும்!",
            IndianLanguage.TELUGU to "కోచ్ {coach}లో ఇప్పటికే విక్రేత ఉన్నారు. కోచ్ {altCoach}కి వెళ్లండి!",
            IndianLanguage.GUJARATI to "કોચ {coach}માં પહેલેથી જ વિક્રેતા છે. કોચ {altCoach}માં જાઓ!",
            IndianLanguage.KANNADA to "ಕೋಚ್ {coach}ನಲ್ಲಿ ಈಗಾಗಲೇ ವ್ಯಾಪಾರಿ ಇದ್ದಾರೆ. ಕೋಚ್ {altCoach}ಗೆ ಹೋಗಿ!",
            IndianLanguage.ODIA to "କୋଚ୍ {coach} ରେ ପୂର୍ବରୁ ବିକ୍ରେତା ଅଛନ୍ତି। କୋଚ୍ {altCoach} କୁ ଯାଆନ୍ତୁ!",
            IndianLanguage.PUNJABI to "ਕੋਚ {coach} ਵਿੱਚ ਪਹਿਲਾਂ ਤੋਂ ਵਿਕਰੇਤਾ ਹੈ। ਕੋਚ {altCoach} ਵਿੱਚ ਜਾਓ!",
            IndianLanguage.MALAYALAM to "കോച്ച് {coach}ൽ ഇതിനകം വെണ്ടർ ഉണ്ട്. കോച്ച് {altCoach}ലേക്ക് പോകുക!"
        ),
        "fair_distribution_banner" to mapOf(
            IndianLanguage.ENGLISH to "Fair Income Dispatch Active: Prioritizing vendors with least sales today",
            IndianLanguage.HINDI to "समान आय वितरण सक्रिय: आज कम बिक्री वाले फेरीवालों को प्राथमिकता",
            IndianLanguage.BENGALI to "ন্যায্য আয় বন্টন সক্রিয়: কম বিক্রি হওয়া হকারদের অগ্রাধিকার",
            IndianLanguage.MARATHI to "समान उत्पन्न वाटप सक्रिय: आज कमी विक्री झालेल्या विक्रेत्यांना प्राधान्य",
            IndianLanguage.TAMIL to "நியாயமான வருமான விநியோகம்: குறைவான விற்பனை செய்தோருக்கு முன்னுரிமை",
            IndianLanguage.TELUGU to "సమాన ఆదాయ పంపిణీ: నేడు తక్కువ అమ్మకాలు ఉన్న విక్రేతలకు ప్రాధాన్యత",
            IndianLanguage.GUJARATI to "સમાન આવક વહેંચણી: ઓછું વેચાણ ધરાવતા ફેરિયાઓને પ્રાધાન્ય",
            IndianLanguage.KANNADA to "ನ್ಯಾಯಯುತ ಆದಾಯ ಹಂಚಿಕೆ: ಕಡಿಮೆ ಮಾರಾಟವಾದವರಿಗೆ ಆದ್ಯತೆ",
            IndianLanguage.ODIA to "ସମାନ ଆୟ ବଣ୍ଟନ: କମ୍ ବିକ୍ରି ହୋଇଥିବା ବିକ୍ରେତାଙ୍କୁ ପ୍ରାଥମିକତା",
            IndianLanguage.PUNJABI to "ਬਰਾਬਰ ਕਮਾਈ ਵੰਡ: ਘੱਟ ਵਿਕਰੀ ਵਾਲਿਆਂ ਨੂੰ ਪਹਿਲ",
            IndianLanguage.MALAYALAM to "ന്യായമായ വരുമാന വിതരണം സജീവം"
        ),
        "monthly_budget_title" to mapOf(
            IndianLanguage.ENGLISH to "Monthly Food Budget & Commute Expenses",
            IndianLanguage.HINDI to "मासिक नाश्ता बजट व दैनिक यात्रा खर्च",
            IndianLanguage.BENGALI to "মাসিক খাবারের বাজেট ও যাতায়াত খরচ",
            IndianLanguage.MARATHI to "मासिक खाद्यान्न बजेट व प्रवास खर्च",
            IndianLanguage.TAMIL to "மாதாந்திர உணவு பட்ஜெட் & பயண செலவு",
            IndianLanguage.TELUGU to "నెలవారీ ఆహార బడ్జెట్ & ప్రయాణ ఖర్చులు",
            IndianLanguage.GUJARATI to "માસિક નાસ્તા બજેટ અને મુસાફરી ખર્ચ",
            IndianLanguage.KANNADA to "ಮಾಸಿಕ ಆಹಾರ ಬಜೆಟ್ & ಪ್ರಯಾಣ ವೆಚ್ಚ",
            IndianLanguage.ODIA to "ମାସିକ ଖାଦ୍ୟ ବଜେଟ୍ ଓ ଯାତ୍ରା ଖର୍ଚ୍ଚ",
            IndianLanguage.PUNJABI to "ਮਾਸਿਕ ਭੋਜਨ ਬਜਟ ਅਤੇ ਯਾਤਰਾ ਖਰਚੇ",
            IndianLanguage.MALAYALAM to "പ്രതിമാസ ഭക്ഷണ ബജറ്റും യാത്രാ ചെലവും"
        ),
        "spent_this_month" to mapOf(
            IndianLanguage.ENGLISH to "Spent This Month",
            IndianLanguage.HINDI to "इस महीने का खर्च",
            IndianLanguage.BENGALI to "এই মাসের খরচ",
            IndianLanguage.MARATHI to "या महिन्याचा खर्च",
            IndianLanguage.TAMIL to "இந்த மாத செலவு",
            IndianLanguage.TELUGU to "ఈ నెల ఖర్చు",
            IndianLanguage.GUJARATI to "આ મહિનાનો ખર્ચ",
            IndianLanguage.KANNADA to "ಈ ತಿಂಗಳ ವೆಚ್ಚ",
            IndianLanguage.ODIA to "ଏହି ମାସର ଖର୍ଚ୍ଚ",
            IndianLanguage.PUNJABI to "ਇਸ ਮਹੀਨੇ ਦਾ ਖਰਚਾ",
            IndianLanguage.MALAYALAM to "ഈ മാസത്തെ ചെലവ്"
        ),
        "savings_vs_station" to mapOf(
            IndianLanguage.ENGLISH to "Saved vs Station Retail",
            IndianLanguage.HINDI to "स्टेशन दुकानों की तुलना में बचत",
            IndianLanguage.BENGALI to "স্টেশন দোকানের তুলনায় সাশ্রয়",
            IndianLanguage.MARATHI to "स्टेशन दुकानांच्या तुलनेत बचत",
            IndianLanguage.TAMIL to "நிலையக் கடைகளை விட சேமிப்பு",
            IndianLanguage.TELUGU to "స్టేషన్ దుకాణాల కంటే ఆదా",
            IndianLanguage.GUJARATI to "સ્ટેશનની દુકાનો કરતાં બચત",
            IndianLanguage.KANNADA to "ನಿಲ್ದಾಣದ ಅಂಗಡಿಗಳಿಗಿಂತ ಉಳಿತಾಯ",
            IndianLanguage.ODIA to "ଷ୍ଟେସନ ଦୋକାନ ଅପେକ୍ଷା ସଞ୍ଚୟ",
            IndianLanguage.PUNJABI to "ਸਟੇਸ਼ਨ ਦੀਆਂ ਦੁਕਾਨਾਂ ਨਾਲੋਂ ਬੱਚਤ",
            IndianLanguage.MALAYALAM to "സ്റ്റേഷൻ കടകളേക്കാൾ ലാഭം"
        ),
        "vendor_earnings_today" to mapOf(
            IndianLanguage.ENGLISH to "Today's Sales & Deliveries",
            IndianLanguage.HINDI to "आज की कुल बिक्री व डिलेवरी",
            IndianLanguage.BENGALI to "আজকের মোট বিক্রি ও ডেলিভারি",
            IndianLanguage.MARATHI to "आजची एकूण विक्री व डिलिव्हरी",
            IndianLanguage.TAMIL to "இன்றைய விற்பனை & வருமானம்",
            IndianLanguage.TELUGU to "నేటి అమ్మకాలు & ఆదాయం",
            IndianLanguage.GUJARATI to "આજનું કુલ વેચાણ અને આવક",
            IndianLanguage.KANNADA to "ಇಂದಿನ ಒಟ್ಟು ಮಾರಾಟ",
            IndianLanguage.ODIA to "ଆଜିର ମୋଟ ବିକ୍ରି",
            IndianLanguage.PUNJABI to "ਅੱਜ ਦੀ ਕੁੱਲ ਵਿਕਰੀ",
            IndianLanguage.MALAYALAM to "ഇന്നത്തെ വിൽപ്പനയും വരുമാനവും"
        ),
        "filter_all" to mapOf(
            IndianLanguage.ENGLISH to "All Items",
            IndianLanguage.HINDI to "सभी नाश्ते",
            IndianLanguage.BENGALI to "সব খাবার",
            IndianLanguage.MARATHI to "सर्व खाद्यपदार्थ",
            IndianLanguage.TAMIL to "அனைத்தும்",
            IndianLanguage.TELUGU to "అన్ని వస్తువులు",
            IndianLanguage.GUJARATI to "બધી વસ્તુઓ",
            IndianLanguage.KANNADA to "ಎಲ್ಲಾ ತಿಂಡಿಗಳು",
            IndianLanguage.ODIA to "ସବୁ ଖାଦ୍ୟ",
            IndianLanguage.PUNJABI to "ਸਾਰੀਆਂ ਚੀਜ਼ਾਂ",
            IndianLanguage.MALAYALAM to "എല്ലാം"
        ),
        "filter_veg" to mapOf(
            IndianLanguage.ENGLISH to "Pure Veg",
            IndianLanguage.HINDI to "शुद्ध शाकाहारी",
            IndianLanguage.BENGALI to "নিরামিষ",
            IndianLanguage.MARATHI to "शुद्ध शाकाहारी",
            IndianLanguage.TAMIL to "சைவம்",
            IndianLanguage.TELUGU to "శుద్ధ శాకాహారం",
            IndianLanguage.GUJARATI to "શુદ્ધ શાકાહારી",
            IndianLanguage.KANNADA to "ಶುದ್ಧ ಸಸ್ಯಾಹಾರ",
            IndianLanguage.ODIA to "ଶୁଦ୍ଧ ଶାକାହାରୀ",
            IndianLanguage.PUNJABI to "ਸ਼ੁੱਧ ਸ਼ਾਕਾਹਾਰੀ",
            IndianLanguage.MALAYALAM to "ശുദ്ധ സസ്യാഹാരം"
        ),
        "filter_jain" to mapOf(
            IndianLanguage.ENGLISH to "Jain (No Onion/Garlic)",
            IndianLanguage.HINDI to "जैन (बिना प्याज/लहसुन)",
            IndianLanguage.BENGALI to "জৈন খাবার (পেঁয়াজ-রসুন ছাড়া)",
            IndianLanguage.MARATHI to "जैन (कांदा/लसूण विरहित)",
            IndianLanguage.TAMIL to "சைவ உணவு (வெங்காயம்/பூண்டு இல்லை)",
            IndianLanguage.TELUGU to "జైన ఆహారం",
            IndianLanguage.GUJARATI to "જૈન (ડુંગળી/લસણ વગર)",
            IndianLanguage.KANNADA to "ಜೈನ ಆಹಾರ",
            IndianLanguage.ODIA to "ଜୈନ ଖାଦ୍ୟ",
            IndianLanguage.PUNJABI to "ਜੈਨ ਖਾਣਾ",
            IndianLanguage.MALAYALAM to "ജൈന ഭക്ഷണം"
        ),
        "filter_senior_soft" to mapOf(
            IndianLanguage.ENGLISH to "Senior Friendly (Soft / Low Spice)",
            IndianLanguage.HINDI to "बुजुर्गों के लिए (नरम / कम मिर्च)",
            IndianLanguage.BENGALI to "বয়োজ্যেষ্ঠদের উপযোগী (নরম / কম ঝাল)",
            IndianLanguage.MARATHI to "ज्येष्ठांसाठी (मऊ / कमी तिखट)",
            IndianLanguage.TAMIL to "முதியோருக்கானது (மென்மையான / காரமற்ற)",
            IndianLanguage.TELUGU to "సీనియర్లకు అనుకూలం (మృదువైనది)",
            IndianLanguage.GUJARATI to "વડીલો માટે (નરમ / ઓછી તીખાશ)",
            IndianLanguage.KANNADA to "ಹಿರಿಯರಿಗೆ ಸುಲಭ ಆಹಾರ",
            IndianLanguage.ODIA to "ବରିଷ୍ଠଙ୍କ ପାଇଁ (ନରମ / କମ୍ ମସଲା)",
            IndianLanguage.PUNJABI to "ਬਜ਼ੁਰਗਾਂ ਲਈ (ਨਰਮ / ਘੱਟ ਮਿਰਚ)",
            IndianLanguage.MALAYALAM to "മുതിർന്നവർക്ക് അനുയോജ്യം"
        ),
        "filter_under_30" to mapOf(
            IndianLanguage.ENGLISH to "Under ₹30",
            IndianLanguage.HINDI to "₹30 से कम",
            IndianLanguage.BENGALI to "₹৩০ এর নিচে",
            IndianLanguage.MARATHI to "₹३० पेक्षा कमी",
            IndianLanguage.TAMIL to "₹30-க்கு கீழ்",
            IndianLanguage.TELUGU to "₹30 లోపు",
            IndianLanguage.GUJARATI to "₹૩૦ થી ઓછું",
            IndianLanguage.KANNADA to "₹30 ಕ್ಕಿಂತ ಕಡಿಮೆ",
            IndianLanguage.ODIA to "₹୩୦ ରୁ କମ୍",
            IndianLanguage.PUNJABI to "₹30 ਤੋਂ ਘੱਟ",
            IndianLanguage.MALAYALAM to "₹30-ൽ താഴെ"
        ),
        "nav_home" to mapOf(
            IndianLanguage.ENGLISH to "Home",
            IndianLanguage.HINDI to "होम",
            IndianLanguage.BENGALI to "হোম",
            IndianLanguage.MARATHI to "मुख्य",
            IndianLanguage.TAMIL to "முகப்பு",
            IndianLanguage.TELUGU to "హోమ్",
            IndianLanguage.GUJARATI to "હોમ",
            IndianLanguage.KANNADA to "ಮುಖಪುಟ",
            IndianLanguage.ODIA to "ମୁଖ୍ୟ",
            IndianLanguage.PUNJABI to "ਮੁੱਖ",
            IndianLanguage.MALAYALAM to "ഹോം"
        ),
        "nav_coach_radar" to mapOf(
            IndianLanguage.ENGLISH to "Coach Radar",
            IndianLanguage.HINDI to "कोच रडार",
            IndianLanguage.BENGALI to "কোচ রাডার",
            IndianLanguage.MARATHI to "डबा रडार",
            IndianLanguage.TAMIL to "கோச் ரேடார்",
            IndianLanguage.TELUGU to "కోచ్ రాడార్",
            IndianLanguage.GUJARATI to "કોચ રડાર",
            IndianLanguage.KANNADA to "ಕೋಚ್ ರೇಡಾರ್",
            IndianLanguage.ODIA to "କୋଚ୍ ରାଡାର",
            IndianLanguage.PUNJABI to "ਕੋਚ ਰਾਡਾਰ",
            IndianLanguage.MALAYALAM to "കോച്ച് റഡാർ"
        ),
        "nav_budget" to mapOf(
            IndianLanguage.ENGLISH to "Budget & Ledger",
            IndianLanguage.HINDI to "बजट व हिसाब",
            IndianLanguage.BENGALI to "বাজেট ও হিসাব",
            IndianLanguage.MARATHI to "बजेट व हिशोब",
            IndianLanguage.TAMIL to "பட்ஜெட் & கணக்கு",
            IndianLanguage.TELUGU to "బడ్జెట్ & లెడ్జర్",
            IndianLanguage.GUJARATI to "બજેટ અને હિસાબ",
            IndianLanguage.KANNADA to "ಬಜೆಟ್ & ಲೆಡ್ಜರ್",
            IndianLanguage.ODIA to "ବଜେଟ୍ ଓ ହିସାବ",
            IndianLanguage.PUNJABI to "ਬਜਟ ਅਤੇ ਹਿਸਾਬ",
            IndianLanguage.MALAYALAM to "ബജറ്റും കണക്കും"
        ),
        "nav_profile" to mapOf(
            IndianLanguage.ENGLISH to "Profile & Settings",
            IndianLanguage.HINDI to "प्रोफ़ाइल व सेटिंग्स",
            IndianLanguage.BENGALI to "প্রোফাইল ও সেটিংস",
            IndianLanguage.MARATHI to "प्रोफाइल व सेटिंग",
            IndianLanguage.TAMIL to "சுயவிவரம்",
            IndianLanguage.TELUGU to "ప్రొఫైల్",
            IndianLanguage.GUJARATI to "પ્રોફાઇલ",
            IndianLanguage.KANNADA to "ಪ್ರೊಫೈಲ್",
            IndianLanguage.ODIA to "ପ୍ରୋଫାଇଲ",
            IndianLanguage.PUNJABI to "ਪ੍ਰੋਫਾਈਲ",
            IndianLanguage.MALAYALAM to "പ്രൊഫൈൽ"
        ),
        "active_train_status" to mapOf(
            IndianLanguage.ENGLISH to "Live Local Train Route Tracking",
            IndianLanguage.HINDI to "लाइव लोकल ट्रेन मार्ग व स्टेशन स्थिति",
            IndianLanguage.BENGALI to "লাইভ লোকাল ট্রেন ও স্টেশন ট্র্যাকিং",
            IndianLanguage.MARATHI to "थेट लोकल ट्रेन मार्ग व स्थानक स्थिती",
            IndianLanguage.TAMIL to "நேரடி ரயில் பாதை கண்காணிப்பு",
            IndianLanguage.TELUGU to "లైవ్ లోకల్ రైలు ట్రాకింగ్",
            IndianLanguage.GUJARATI to "લાઇવ લોકલ ટ્રેન રૂટ ટ્રેકિંગ",
            IndianLanguage.KANNADA to "ಲೈವ್ ಲೋಕಲ್ ರೈಲು ಟ್ರ್ಯಾಕಿಂಗ್",
            IndianLanguage.ODIA to "ଲାଇଭ୍ ଲୋକାଲ ଟ୍ରେନ୍ ଟ୍ରାକିଂ",
            IndianLanguage.PUNJABI to "ਲਾਈਵ ਲੋਕਲ ਟ੍ਰੇਨ ਟ੍ਰੈਕਿੰਗ",
            IndianLanguage.MALAYALAM to "തത്സമയ ട്രെയിൻ ട്രാക്കിംഗ്"
        ),
        "next_station" to mapOf(
            IndianLanguage.ENGLISH to "Next Station",
            IndianLanguage.HINDI to "अगला स्टेशन",
            IndianLanguage.BENGALI to "পরবর্তী স্টেশন",
            IndianLanguage.MARATHI to "पुढील स्थानक",
            IndianLanguage.TAMIL to "அடுத்த நிலையம்",
            IndianLanguage.TELUGU to "తదుపరి స్టేషన్",
            IndianLanguage.GUJARATI to "આગામી સ્ટેશન",
            IndianLanguage.KANNADA to "ಮುಂದಿನ ನಿಲ್ದಾಣ",
            IndianLanguage.ODIA to "ପରବର୍ତ୍ତୀ ଷ୍ଟେସନ",
            IndianLanguage.PUNJABI to "ਅਗਲਾ ਸਟੇਸ਼ਨ",
            IndianLanguage.MALAYALAM to "അടുത്ത സ്റ്റേഷൻ"
        ),
        "stop_duration" to mapOf(
            IndianLanguage.ENGLISH to "Stop: 45 seconds (Vendors boarding available)",
            IndianLanguage.HINDI to "ठहराव: 45 सेकंड (फेरीवाले कोच में उपलब्ध)",
            IndianLanguage.BENGALI to "স্টপেজ: ৪৫ সেকেন্ড (হকার সংযোগ চালু)",
            IndianLanguage.MARATHI to "थांबा: ४५ सेकंद (फेरीवाले डब्यात उपलब्ध)",
            IndianLanguage.TAMIL to "நிறுத்தம்: 45 வினாடிகள்",
            IndianLanguage.TELUGU to "నిలుపుదల: 45 సెకన్లు",
            IndianLanguage.GUJARATI to "રોકાણ: 45 સેકન્ડ",
            IndianLanguage.KANNADA to "ನಿಲುಗಡೆ: 45 ಸೆಕೆಂಡುಗಳು",
            IndianLanguage.ODIA to "ରହଣି: ୪୫ ସେକେଣ୍ଡ",
            IndianLanguage.PUNJABI to "ਠਹਿਰਾਅ: 45 ਸਕਿੰਟ",
            IndianLanguage.MALAYALAM to "നിർത്തൽ: 45 സെക്കൻഡ്"
        ),
        "record_sale_btn" to mapOf(
            IndianLanguage.ENGLISH to "Record Completed Sale",
            IndianLanguage.HINDI to "बिक्री दर्ज करें (+₹)",
            IndianLanguage.BENGALI to "বিক্রি নথিভুক্ত করুন",
            IndianLanguage.MARATHI to "विक्री नोंदवा (+₹)",
            IndianLanguage.TAMIL to "விற்பனையை பதிவு செய்",
            IndianLanguage.TELUGU to "అమ్మకం నమోదు చేయండి",
            IndianLanguage.GUJARATI to "વેચાણ નોંધો",
            IndianLanguage.KANNADA to "ಮಾರಾಟ ದಾಖಲಿಸಿ",
            IndianLanguage.ODIA to "ବିକ୍ରି ରେକର୍ଡ କରନ୍ତୁ",
            IndianLanguage.PUNJABI to "ਵਿਕਰੀ ਦਰਜ ਕਰੋ",
            IndianLanguage.MALAYALAM to "വിൽപ്പന രേഖപ്പെടുത്തുക"
        ),
        "audio_alert_on" to mapOf(
            IndianLanguage.ENGLISH to "Audio & Haptic Alert Active",
            IndianLanguage.HINDI to "आवाज व कंपन अलर्ट चालू",
            IndianLanguage.BENGALI to "শব্দ ও কম্পন সতর্কতা চালু",
            IndianLanguage.MARATHI to "ध्वनी व कंपन इशारा सक्रिय",
            IndianLanguage.TAMIL to "ஒலி மற்றும் அதிர்வு விழிப்பூட்டல்",
            IndianLanguage.TELUGU to "శబ్ద మరియు కంపన హెచ్చరిక",
            IndianLanguage.GUJARATI to "અવાજ અને કંપન ચેતવણી",
            IndianLanguage.KANNADA to "ಧ್ವನಿ ಮತ್ತು ಕಂಪನ ಎಚ್ಚರಿಕೆ",
            IndianLanguage.ODIA to "ଶବ୍ଦ ଓ କମ୍ପନ ସତର୍କତା",
            IndianLanguage.PUNJABI to "ਆਵਾਜ਼ ਅਤੇ ਕੰਬਣੀ ਚਿਤਾਵਨੀ",
            IndianLanguage.MALAYALAM to "ശബ്ദ അലേർട്ട് സജീവം"
        )
    )
}
